chore(repo): Add script to add ArtifactHub changelog annotations

diff --git a/.github/workflows/update-mds.yml b/.github/workflows/update-mds.yml
--- a/.github/workflows/update-mds.yml
+++ b/.github/workflows/update-mds.yml
@@ -37,11 +37,48 @@ jobs:
             echo "$chart: values.yaml changes detected"
             echo "Updating README.md for $chart"
             readme-generator --values "$chart/values.yaml" --readme "$chart/README.md"
-            # Check for changes and commit if necessary
+          done
+      - name: Update ArtifactHub change annotations
+        shell: bash
+        run: |
+          PR_TITLE="${{ github.event.pull_request.title }}"
+          add_changes_to_chart_yaml() {
+            local file_path="Chart.yaml"
+            local changes=$1
+            if [ ! -f "$file_path" ]; then
+              echo "Chart.yaml not found!"
+              exit 1
+            fi
+            chart=$(cat "$file_path")
+            # Check if annotations exist
+            if ! grep -q "annotations:" <<< "$chart"; then
+              chart=$(echo "$chart"$'\n'annotations:)
+            fi
+            # Check if artifacthub.io/changes annotation exists
+            if ! grep -q "artifacthub.io/changes:" <<< "$chart"; then
+              chart=$(echo "$chart"$'\n'  artifacthub.io/changes: | sed 's/^/  /')
+            fi
+            # Append the new changes to the existing ones
+            chart=$(echo "$chart"$'\n'"$changes" | sed 's/^/  /')
+            echo "$chart" > "$file_path"
+          }
+          # Parse PR title to create changelog entries
+          changes=""
+          if [[ $PR_TITLE == *"feat:"* ]]; then
+            changes="$changes"$'\n'  - kind: feature
+            changes="$changes"$'\n'    description: "${PR_TITLE#*: }"
+          elif [[ $PR_TITLE == *"fix:"* ]]; then
+            changes="$changes"$'\n'  - kind: bugfix
+            changes="$changes"$'\n'    description: "${PR_TITLE#*: }"
+          fi
+          add_changes_to_chart_yaml "$changes"
+      - name: Commit and push changes
+        run: |
+          cd charts || exit 1
+            for chart in */; do
+              # Check for changes and commit if necessary
             if git status -s | grep "$chart"; then
               git add "$chart" && git commit -m "docs(${chart%*/}): Update values in README.md" # Remove trailing slash
+              git push
             fi
           done
-      - name: Push changes
-        run: |
-          git push
