chore(repo): Split into two jobs

diff --git a/.github/workflows/update-mds.yml b/.github/workflows/update-mds.yml
--- a/.github/workflows/update-mds.yml
+++ b/.github/workflows/update-mds.yml
@@ -6,10 +6,15 @@ on:
       - main
 
 jobs:
-  update-readme:
+  gather-information:
     runs-on: ubuntu-latest
     permissions:
-      contents: write
+      contents: read
+      pull-requests: read
+    outputs:
+      chart: ${{ steps.gather-information.outputs.chart }}
+      values_changed: ${{ steps.gather-information.outputs.values_changed }}
+      failed: ${{ steps.gather-information.outputs.failed }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -18,18 +23,15 @@ jobs:
           ref: ${{github.event.pull_request.head.ref}}
           repository: ${{github.event.pull_request.head.repo.full_name}}
           token: ${{secrets.CONTANE_BOT_TOKEN}}
-      - name: Configure Git
-        run: |
-          git config user.name "contane-bot"
-          git config user.email "160241315+contane-bot@users.noreply.github.com"
       - name: Gather pull request information
+        id: gather-information
         run: |
           NUM_CHANGED_CHARTS=0
           cd charts || exit 1
           for chart in */; do
             # Check if values.yaml has changed
             if git diff --name-only HEAD~1 | grep -q "$chart"; then
-              echo "$chart: Changes detected"
+              echo "$chart: No changes detected"
               continue
             fi
             echo "$chart: Changes detected"
@@ -37,24 +39,51 @@ jobs:
             echo "CHANGED_CHART=$chart" >> "$GITHUB_ENV"
           done
           if [ "$NUM_CHANGED_CHARTS" -eq 0 ]; then
-            echo "No charts have changed"
-            exit 0
+            echo "ERROR=No charts have changed" >> "$GITHUB_ENV"
+            echo "FAILED=true" >> "$GITHUB_ENV
           fi
           if [ "$NUM_CHANGED_CHARTS" -gt 1 ]; then
-              echo "Multiple charts have changed, only update one Chart per PR"
-              exit 1
+              echo "ERROR=Multiple charts have changed, only update one Chart per PR" >> "$GITHUB_ENV"
+              echo "FAILED=true" >> "$GITHUB_ENV
           fi
           if git diff --name-only HEAD~1 | grep -q "$CHANGED_CHART/values.yaml"; then
             echo "$CHANGED_CHART: No values.yaml changes detected"
-            exit 0
           fi
           echo "$CHANGED_CHART: values.yaml changes detected"
           echo "VALUES_CHANGED=true" >> "$GITHUB_ENV"
+      # Using actions/github-scripts because using exit 1 in the script above would not provide any output
+      # Source: https://github.community/t/no-output-on-process-completed-with-exit-code-1/123821/3
+      - id: show-error
+        name: Show error
+        if: ${{ steps.gather-inforation.outputs.failed }}
+        uses: actions/github-script@7.0.1
+        with:
+          script: |
+            if (!${{ steps.gather-inforation.outputs.error }}) {
+              core.setFailed(${{ steps.gather-inforation.outputs.error }});
+            }
+  update-documentation:
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    if: ${{ needs.gather-information.outputs.failed != 'true' }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+          token: ${{ secrets.CONTANE_BOT_TOKEN }}
+      - name: Configure Git
+        run: |
+          git config user.name "contane-bot"
+          git config user.email "160241315+contane-bot@users.noreply.github.com"
       - name: Install readme-generator-for-helm
-        if: env.VALUES_CHANGED == 'true'
+        if: ${{ needs.gather-information.outputs.values_changed == 'true' }}
         run: npm install -g @bitnami/readme-generator-for-helm@2.6.1
       - name: Update README.md
-        if: env.VALUES_CHANGED == 'true'
+        if: ${{ needs.gather-information.outputs.values_changed == 'true' }}
         shell: bash
         run: |
           cd charts || exit 1
